title: Materiale Ingegneria Free
description: >- # this means to ignore newlines until "baseurl:"
  Trasferito su github.com/MaterialeIngegneriaFree/materiale-ingegneria-free/
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://materialeingegneriafree.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll/minima
theme: jekyll-theme-minimal

plugins:
 - jekyll-feed
 - jekyll-sitemap
  
# Theme Settings
header_pages:
  - index.markdown
